### ISSUE TITLE
2.0 - _ is not defined

### ISSUE THREAD

**Issue by MichaelJCole** [jnordberg/wintersmith#118]
![index jade](https://f.cloud.github.com/assets/1504790/569990/f6f98480-c722-11e2-8c10-1a27ed1ffa24.jpg)
![layout jade](https://f.cloud.github.com/assets/1504790/569991/f6f846ce-c722-11e2-8226-032ca5f7543b.jpg)

Hi, cool project!

I just upgraded to 2.0 and am getting this error when requesting / 

The error is happening when jade tries to compile the index.jade template

```
ReferenceError: index.jade:6
    4| 
    5|   // Get a list of services from the content map
  > 6|   - var services = _.chain(contents.services._.directories).map(function(item) {
    7|   -   return item.index
    8|   - }).compact().sortBy(function(item) {
    9|   -   return item._metadata.order

_ is not defined
    at eval (eval at <anonymous> (/usr/lib/node_modules/jade/lib/jade.js:171:8), <anonymous>:278:16)
```

It's the first _ from my testing.  I copied my 1.x templates into the 2.x blog example project and edited the config.json.  

My templates are attached.  What am I missing?  I did a npm install to get local copies of the dependencies.

**Comment by askdesigners** [comment]
Ya I just had the same issue. If you rename the articles folder the pagination plugin dies.

**Comment by MichaelJCole** [comment]
Lol, almost exactly 2 years later, I have this problem, google, and find my own bug.  Here's how I fixed it in paginator.coffee  (it's the first if statement):

```
  getArticles = (contents) ->
    if not contents[options.articles]?
      return []
    # helper that returns a list of articles found in *contents*
    # note that each article is assumed to have its own directory in the articles directory
    articles = contents[options.articles]._.directories.map (item) -> item.index
    # skip articles that does not have a template associated
    articles = articles.filter (item) -> item.template isnt 'none'
    # sort article by date
    articles.sort (a, b) ->
      return Date.parse(b.metadata.publishedDate) - Date.parse(a.metadata.publishedDate)
    return articles
```
