### ISSUE TITLE
Expose metadata from jade template errors

### ISSUE THREAD

**Issue by MichaelJCole** [jnordberg/wintersmith#124]
Hi, I had a confusing error message from Wintersmith.

I got this error - when the problem was actually in another file (a mixin)

``` javascript
  error index.html: /home/michaelcole/scm/smallsites/michaelcole.com/templates/index.jade:17
    15|   - }).compact().sortBy(function(item) {
    16|   -   console.log(item.metadata.title)
  > 17|   -   return item.metadata.title
    18|   - }).value();
    19| 
    20|   // Main article
```

Cannot read property 'order' of undefined

The problem was from a mixin included at index.jade:23.  The error was at mixins.jade:17.

I zipped a copy of the code and can send it to you if you like.

Thanks!

Mike

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
