### ISSUE TITLE
What are views?

### ISSUE THREAD

**Issue by tnguyen14** [jnordberg/wintersmith#132]
The readme mentions that views is one of the 3 components of the framework.

However, I can't find any `views` folder when I installed wintersmith. In the `README` blog post, the `views` folder is also mentioned. 

Could someone explain what it is, how I can use it and where I can find more documentation on it?

Thanks.

**Comment by orangganjil** [comment]
Hi, is there any documentation or examples for views yet? I am trying to move my blog page to a separate page off of the main index.html (e.g., /articles/index.html or /blog.html). I could get a hacked-together archive.jade template to do it, but I have a feeling that views would be better.

Is there anything available? My searches have come up empty.

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
