### ISSUE TITLE
Syntax highlighting for code

### ISSUE THREAD

**Issue by tusharmath** [jnordberg/wintersmith#140]
Incase some code is written in a block, can we have syntax highlighting for it?

**Comment by gagan-bansal** [comment]
I also want to switch theme 'tomorrow' to some other. @tarruda could you find the solution?

**Comment by tarruda** [comment]
> I also want to switch theme 'tomorrow' to some other. @tarruda could you find the solution?

I couldn't, sorry

**Comment by gagan-bansal** [comment]
It seems then `.function` etc classes in `main.css` file need be changed manually.

**Comment by gagan-bansal** [comment]
Regarding the blog templates, path in the installed `wintersmith` is
```
/path/to/wintersmith/examples/
```
There are three templates in the folder `basic`  `blog`  and `webapp`. Whereas default is `blog` 

And regarding the style change in `your-project/contents/css/main.css` the default theme is **Tomorrow** in separate section. So this theme can be replaced manually with many [themes](http://jmblog.github.io/color-themes-for-highlightjs/) by @jmblog 

But there are many [more themes](https://highlightjs.org/static/demo/) in highlight.js demo. In these new themes every class is prefixed with **'hljs-'**. So these new themes can not be used directly. There is nice option in the wintersmith to prefix the class name for highlight.js classes. 
Go to

```
/path/to/wintersmith/lib/plugins/markdown.js
```
Change the highlight.js config parameter as
```javascript
  hljs.configure({
    classPrefix: 'hljs-'
  }); 
```
So now you can easily replace the highlight.js themes in wintersmith.

**Comment by adonespitogo** [comment]
A cleaner way is to make use of the `config.json`

```json
  "markdown": {
    "smartLists": true,
    "smartypants": true
  },
  "highlightjs": {
    "classPrefix": "hljs-"
  }
```
