### ISSUE TITLE
Plugin for Deploying to Github pages or Heroku

### ISSUE THREAD

**Issue by tusharmath** [jnordberg/wintersmith#151]
Do we have a plugin which can be used to deploy to GH pages or heroku from command line? 

Something like this - 

``` bash
wintersmith publish
```

One can configure the settings using the Config.json file and then publish it to gh-pages etc. Right now I have a separate Grunt file which does this. 

The best thing would be then to link this publish feature to Travis-CI so that your system doesn't have to do so much of load bearing.

**PS:** _Maybe it's just me who is doing it all wrong, if that's true then can someone suggest a more simpler way of doing the same?_

**Comment by gagan-bansal** [comment]
I liked Stephan Hoyer [idea](http://stephanhoyer.github.io/articles/001-building-wintersmith-blog/) to create a src directory in your github page project and build path as '../'

Do you see any issue with it?

**Comment by gagan-bansal** [comment]
**Please do not take my above recommendation for  Stephan Hoyer** [idea](http://stephanhoyer.github.io/articles/001-building-wintersmith-blog/)

A big issue in this structure
```"output": "../"```
if you run:
```wintersmith build --clean```
You are gone, whole project is wiped out.
It happened with me and many of my changes had gone and the whole git project also.

OR please correct me If I am doing something wrong.
