### ISSUE TITLE
How to debug print an object from jade?

### ISSUE THREAD

**Issue by MichaelJCole** [jnordberg/wintersmith#155]
Hi, this is more of a support request.

What's the best way to debug print a content node in a Jade template?

I've tried 

```
               p!= JSON.stringify(process, null, 2)
```

```
index.html: /home/michaelcole/scm/smallsites/powma.com/templates/index.jade:113
    111|                 h3!= metadata.title
    112|                 strong!= metadata.subTitle
  > 113|                 p!= JSON.stringify(process, null, 2)
    114| 
    115| 
    116|   p a
Converting circular structure to JSON
```

And also tried:

```
               p!= require('util').inspect(process)
```

```
index.html:     /home/michaelcole/scm/smallsites/powma.com/templates/index.jade:113
    111|                 h3!= metadata.title
    112|                 strong!= metadata.subTitle
  > 113|                 p!= require('util').inspect(process)
    114| 
    115| 
    116|   p a
    undefined is not a function
```

The best I could come up with is from here, but it's a bit much for a quick debug statement:
http://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json

```
                - var cache = [];
                - str = JSON.stringify(process, function(key, value) {
                -     if (typeof value === 'object' && value !== null) {
                -     if (cache.indexOf(value) !== -1) {
                -       // Circular reference found, discard key
                -       return;
                -     }
                -     // Store value in our collection
                -     cache.push(value);
                -   }
                -   return value;
                - });
                - cache = null; // Enable garbage collection
                pre!= str
```

There's got to be an easier way!

**Comment by lanjeason** [comment]
yes, but it is like console.log, they have the same meaning.

**Comment by magedahmed** [comment]
What if you want to debug a jade file breaking the build? I think console output will be very useful.

**Comment by sjlehn** [comment]
If you're just printing to the console it's not necessary to wrap it in a div.  Just

`- console.log('my output')`

will work.  Adding the divs may mess up the display of your page, depending on what you're doing

**Comment by regar007** [comment]
You see your Object in browser console using bellow!
script.
   console.log(!{JSON.stringify(YourObject)})   // one or two spaces before console.log

**Comment by labved** [comment]
> !{JSON.stringify

doesn't work
