### ISSUE TITLE
Detailed template variable reference?

### ISSUE THREAD

**Issue by tyler-johnson** [jnordberg/wintersmith#174]
Hello. I find myself seriously confused as to what variables are available to me when I am developing a Wintersmith site. Is it possible to write up a small wiki page on generic default template variables, namely what the `contents` and `env` objects contain? I also would recommend telling plugin creators to document any special variables that are available in templates.

I would also like to point out a way to see what these variables contain for those struggling with this as I am. In a jade template you can use the following to print the contents to the console:

```
- console.log(contents);
```

Thanks for all your hard work! This project is awesome!

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
