### ISSUE TITLE
Way to list similar pages (e.g. based on categories)

### ISSUE THREAD

**Issue by rapsli** [jnordberg/wintersmith#175]
Is there already a way to list similar pages? Let me quickly describe the usecase:

I have a page and in the footer there is a region "Similar pages". This region would list 5 pages that are similar to the current page.

How to accomplish this? Simpliest method would be: select them by the categories metadata. More advanced, content sensitive methods possible.

Is this currently already possible? If not how could this be accomplished?

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
