### ISSUE TITLE
Guidelines for helping with documentation?

### ISSUE THREAD

**Issue by fvsch** [jnordberg/wintersmith#178]
I’m under the impression that Wintersmith could do with more complete and better structured docs. Personally I had trouble locating some of the information that does exist in the docs, and had to figure out other bits of information in other ways (reading the codebase and experimenting). I see that several issues in the tracker relate to missing documentation.

So, since I’m kinda determined (and have started) to reimplement my website using Wintersmith shortly, and possibly write other sites in the next few months, I was wondering if I could try to help with documentation, and to what extent.

To @jnordberg:
- What’s your view of the current docs and the priorities (if any) for them?
- Should the docs live at https://github.com/jnordberg/wintersmith/wiki ?
- If yes, would it be okay to restructure the docs there considerably?

I’d suggest moving all the main documentation bits (Quick-start, Configuration, Content Plugins, The Page Plugin, Plugins, Using wintersmith programmatically) from wintersmith/README.md to individual wiki pages, and list those in the README (or just the Quick start, then give a link to the remaining docs).

Also, aside from reorganizing (and perhaps improving) existing content, it seems the main missing areas are:
- A templating guide (related: #174).
- At least some information on views (related #132, #56).

I don’t want to promise I’ll do a _lot_ because I’m not sure what available time I’ll have in the coming weeks. But if this bug results in general guidelines for improvements to the docs, then several people can chime in and contribute. :)

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
