### ISSUE TITLE
Image galleries?

### ISSUE THREAD

**Issue by sprugman** [jnordberg/wintersmith#182]
Hi,

I'm evaluating using wintersmith for a project that is pretty heavy with image galleries. How does jekyll deal with that issue? I guess my ideal would be something like:
- I can have a "gallery" page type
- I can have a gallery of galleries, i.e. projects > project slideshow
- I can dump a bunch of images of whatever sizes into a folder in it
- wintersmith will take care of processing the images into thumbnails and full-size(s) according to some settings in a config file somewhere
- on my gallery html page, I add whatever image viewer I want and wintersmith will take care of converting the list of files to a JSON object that's consumed by the slideshow plugin
  - or, I can use some kind of template just to show the images or thumbnails statically on the page.
- also, as a nice to have, it would be good to be able to specify some meta-data about the images somewhere for use in views

Is this possible/easy? If not are there any static site generators that are good at this?

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
