### ISSUE TITLE
build issues with both less and stylus plugins

### ISSUE THREAD

**Issue by jtremback** [jnordberg/wintersmith#192]
I have encountered this problem with both the less and stylus wintersmith plugins. Everything will work fine in the preview server, then when it's time to build, wintersmith throws an error having to do with undefined variables. 

```
  error css/custom.css: variable @body-bg is undefined
```

This variable works fine in preview mode.

This is a huge problem for me right now, because having built a site thinking that wintersmith works, I now cannot deploy. What could be causing this?

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
