### ISSUE TITLE
wintersmith for a static multi-domain build

### ISSUE THREAD

**Issue by jeromew** [jnordberg/wintersmith#201]
Hello,

I would like to use wintersmith to generate several interlinked sites that will be hosted on different domains.

I guess that I could trick wintersmith by using filenames and generate :
build/
  www.domain1.com/
  www.domain2.com/

and maybe modify the url handling to always generate absolute urls.

probably the preview would not work or there should be different url building schemes depending on the fact that we are in preview or build mode.

Has anyone tried to do such thing and found an elegant way to do this ?

Thanks

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
