### ISSUE TITLE
accessing content tree from inside getHtml

### ISSUE THREAD

**Issue by jeromew** [jnordberg/wintersmith#202]
Hello,
I am trying to see how I can resolve urls in markdown to the real urls that getUrl is giving for a contentPlugin.
Currently, 
- [my link](foo.html) is linking relatively to "foo.html"
- [my link](bar.md) is linking relatively to "bar.md"

so in fact (except if i understood something wrong) there is no resolving of bar.md to the url that wintersmith will really give to bar.md after applying the filename.

I am trying to do such resolving but hit a roadblock because getHtml does not receive "contents" in its arguments. With content, we could use contents['bar.md'].url or something like that.

I maybe found one hack to do it but wanted to know your opinion on this and if maybe there is another solution :

```
class MarkdownPage extends env.plugins.Page
...
  getHtml: (base=env.config.baseUrl) ->
    contents = this
    contents = contents.parent while contents.parent
```

This seems to do the trick because each content plugin seem to have a .parent attribute in the content tree, so we can climb to the top from there :-)

what do you think of this idea ?

we could have an algo where we
- look in the content tree if the linked ressource exists. if it exists, use getUrl
- otherwise use the current relative link

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
