### ISSUE TITLE
Prober way of exposing functions/objects to templates?

### ISSUE THREAD

**Issue by aularon** [jnordberg/wintersmith#211]
Hello,

What is the prober way of making an object visible inside templates? In your `wintersmith-livereload` [you are using `env.helpers`](https://github.com/jnordberg/wintersmith-livereload/blob/master/src/index.coffee#L42), and then calling upon it using `!{ env.helpers.livereload() }` inside the template.

In my [`wintersmith-nap`](https://github.com/etabits/wintersmith-nap) plugin, I [added the `nap` object to `env.locals`](https://github.com/etabits/wintersmith-nap/blob/master/src/wintersmith-nap.coffee#L34-L37), and used it inside the template, and it works and can be called like `!= nap.css('main')`

My question is, is it good to utilize `env.locals` this way? Or should I stick with `env.helpers`?

**Comment by reubano** [comment]
This is how I do it

`jade-helpers.coffee`

```coffeescript
module.exports = (env, callback) ->
  class JadeTemplate extends env.plugins.JadeTemplate
    render: (locals, callback) ->
      locals.helper_func = env.helpers.helperFunc

      try
        callback null, new Buffer @fn(locals)
      catch error
        callback error

  env.registerTemplatePlugin '**/*.jade', JadeTemplate
  callback()
```
