### ISSUE TITLE
1.page, 2.page in content.pages

### ISSUE THREAD

**Issue by airtonix** [jnordberg/wintersmith#212]
This is my contents directory:

https://github.com/airtonix/zenobi.us/tree/master/contents

I seem to be getting something like this in my generated data : 

```
each _, item in contents.pages
    [ #{item} ]
```

results in 

```
[ 1.page]
[ 2.page ]
[ about ]
```

Where are these *.page entries coming from ? 
1. they aren't files i created
2. is it the `.` (current directory) and `..` (parent directory)? I can't imagine it would be since they aren't in the `contents.pages.about` tree.

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
