### ISSUE TITLE
After "wintersmith preview" , changing any file results in server crash

### ISSUE THREAD

**Issue by rafaelvasco** [jnordberg/wintersmith#216]
(Win 8.1 x64, Wintersmith 2.0.10)

Changing any file results in server crash. It can't reload the file. For example if i change config.json "name" field to another value and then save this happens

![error](https://f.cloud.github.com/assets/1713623/2144272/18e12594-9383-11e3-9348-21a196da6d28.PNG).

Think it's related to other issues related with 404 after saving or something.

**Comment by justjake** [comment]
fixed reload not working here: https://github.com/justjake/wintersmith
