### ISSUE TITLE
I've been getting a "Cannot read property 'date' of undefined" error during build...

### ISSUE THREAD

**Issue by Adron** [jnordberg/wintersmith#218]
When I run

```
wintersmith build
```

I get the following error

```
  error page/2/index.html: /Users/adron/Codez/deconstructed_gh-pages/ws/templates/index.jade:9
    7|       header
    8|         p.date
  > 9|           span= moment.utc(article.date).format('DD. MMMM YYYY')
    10|         h2
    11|           a(href=article.url)= article.title
    12|       section.content

Cannot read property 'date' of undefined
```

Even though I'm getting this error, when I push the site live after the static site is built w/ 'wintersmith build' with the above error, it still appears to be working fine. The date does indeed show up, the content renders to static files, etc. So even though I'm getting this error things appear to be working. However, with any error I still am cautious continuing to trust everything. Is there a fix or has anyone else figured out what the issue is here? Cheers!

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
