### ISSUE TITLE
Support for multiple paginated sections

### ISSUE THREAD

**Issue by simoncollins** [jnordberg/wintersmith#227]
In my site I'd like to have two different sections of the site paginated separately. It seems the paginator plugin currently supports only a single section if I understand it correctly.

It looks like it would be relatively simple to modify it to support multiple sections while making it backwards compatible with the current functionality.

Happy to submit a PR if you're interested or keen to hear if there's a better way to do this.

Thx.

**Comment by jamshark70** [comment]
I have been trying pretty much all day to hack this for myself, and failing. @simoncollins if you have code, could you please share? This issue is *killing me*...

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
