### ISSUE TITLE
Question about Paginator.coffee

### ISSUE THREAD

**Issue by kilometers** [jnordberg/wintersmith#229]
This is in regards to the example blog that comes with Wintersmith.

I'm able to discern how paginator.coffee generates the index and subsequent pages. However, I don't understand where/when/how the /articles folder is rendered and placed in the /build folder (aka the individual article pages, not the article list pages). If anyone has a clue to share, please do. I've sifted through the code several times but nothing has caught my eye.

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
