### ISSUE TITLE
Page intro property has extra opening <p> tag

### ISSUE THREAD

**Issue by treslumen** [jnordberg/wintersmith#234]
First of all, this problem occurs only with `<span class="more"></span>`, namely `<h2>` and `<hr>` are fine.

![screenshot](http://i.minus.com/iMk91xxwIraZQ.png)

As shown in the screenshot, whenever `<span class="more"></span>` is used, the resulting `intro` ends with an extra `<p>` without a closing tag.

Could you please fix this?

**Comment by jnordberg** [comment]
Cleaning up old issues, feel free to create a new one if this still is a problem.
