### ISSUE TITLE
error Got a change event for item not previously in tree

### ISSUE THREAD

**Issue by andreypopp** [jnordberg/wintersmith#241]
I constantly get errors like:
```
error Got a change event for item not previously in tree: /Users/.../documentation/schema.md~
```
while editing content with Vim.

**Comment by lihop** [comment]
I was having the same problem. Writing and quitting vim (`:wq!`) worked fine, but just writing (`:w!`) would crash the server with that error message.

I found [this issue](https://github.com/paulmillr/chokidar/issues/35) with the chokidar module. [This comment](https://github.com/paulmillr/chokidar/issues/35/#issuecomment-24194926) suggested using `set nowritebackup` as a workaround. I added that line to my `.vimrc` and it solved the issue for me.

**Comment by jnordberg** [comment]
I think this was due to a bug in fsevents, let me know if anyone still has this issue
