### ISSUE TITLE
Asset urls not affected by baseUrl in config.json

### ISSUE THREAD

**Issue by blacksonic** [jnordberg/wintersmith#242]
On localhost everything was just fine, but when i uploaded the generated blog to github, the links translated correctly with baseUrl, but the css is still starting from /css/main.css
Here is the site: http://blacksonic.github.io/blog/

**Comment by morenoh149** [comment]
+1 @jnordberg is a pull request desired?

**Comment by jnordberg** [comment]
Yeah the naming of that option isn't the best..
