### ISSUE TITLE
page undefined when referenced inside paginator plugin template

### ISSUE THREAD

**Issue by mnewt** [jnordberg/wintersmith#243]
I'm seeing inconsistent interaction between the paginator plugin and the page object.

Starting with the 'blog' from examples:

This code renders as expected when inserted into article.jade:

```
p page url is #{ page.url }
```

However, referencing page from inside a paginator template (for example, the index.jade template from the example blog), produces an error

```
index.html: /path/example-blog/templates/index.jade:5
    3| block content
    4|   include author
  > 5|   p page url is #{ page.url }
    6|   each article in articles
    7|     article.article.intro
    8|       header

Cannot read property 'url' of undefined
```

This is not the expected behavior, is it?

**Comment by MichaelJCole** [comment]
Same here.  I enabled the paginator.coffee file from the examples/blog/plugins directory and page was undefined for pages not using the paginator.
