### ISSUE TITLE
Anchor link, relative to folder

### ISSUE THREAD

**Issue by refextu** [jnordberg/wintersmith#267]
When I wan't to link inside of an document (e.g. mysite.md): 
```
[MyTitle](#top)
```
The link is rewritten by wintersmith like this:
```
<a href="http://www.example.com/folder/#top">MyTitle</a>
```
The expected result would be:
```
<a href="#top">MyTitle</a>
```
or 
```
<a href="http://www.example.com/folder/mysite.html#top">MyTitle</a>
```

**Comment by jmike** [comment]
This is an issue for me as well. @refextu did you manage to find a workaround?

**Comment by czechboy0** [comment]
+1
