### ISSUE TITLE
Building LESS file fails with file wasn't found error

### ISSUE THREAD

**Issue by emirotin** [jnordberg/wintersmith#269]
I have a Wintersmith project using LESS.

My `main.less` imports lots of small module files (and a couple of libraries installed through bower) and everything works just fine in `preview` mode.

But it fails when I try to `build` the project.

My `@import`s are relative and I have 

```
"less": {
    "relativeUrls": true
  }
```

in `config.json`. It seems that relative imports are the source of the problem — if I reduce my `main.less` to a single line and change it from `import "settings/settings";` to `import "contents/settings/settings";` it works (well, fails on a different file, but at least goes over this line).

What really surprises me is that it still works in preview mode.

Is it something relatively easy to fix without replacing all imports in all my modules?
Thanks in advance!

**Comment by jnordberg** [comment]
It works in preview mode because the files are built on demand and you never request the footer directly. But in build mode all files are walked over and built. To fix it just add the offending files to your ignore list in config.json,

Sorry for the slow response..

**Comment by emirotin** [comment]
Sorry it just doesn't make sense to me. There are no offending files. Check the sample repo linked above if you're interested

**Comment by jnordberg** [comment]
Check this https://github.com/emirotin/ws-error/pull/1

**Comment by emirotin** [comment]
OK makes sense now. So when you say offensive you mean the files that are dependent and don't have to be compiled on their own. Thanks.

**Comment by jnordberg** [comment]
Yep, that's it. Also the LESS plugin is configured to ignore any file starting with underscore `_` so you can just name your files like that and they will not be compiled individually
