### ISSUE TITLE
Add generator to plugins page

### ISSUE THREAD

**Issue by mmintel** [jnordberg/wintersmith#272]
Hi there,

I was in need to extend wintersmith and nunjucks with some grunt plugins and created a yeoman generator for that. Maybe it's a good idea to add this to your plugin site so this becomes more popular and people help improving it :)

It's still work in progress though

https://github.com/mmintel/generator-wintersmith-nunjucks

**Comment by jnordberg** [comment]
Nice, feel free to add it to the plugins wiki page
