### ISSUE TITLE
baseUrl and preview

### ISSUE THREAD

**Issue by MrSaints** [jnordberg/wintersmith#279]
I'm not sure if this has been brought up before, but when previewing with a `baseUrl` that is set to a website URL (e.g. `http://www.ilikedogs.com/`), it will start the server using that exact path (i.e. `http://localhost:8080/http://www.ilikedogs.com/`). I'd love to have my assets permalink'd (so the image will load in RSS feeds) and modifying `baseUrl` helps. Perhaps there should be two config options (baseUrl and basePath)?

**Comment by jnordberg** [comment]
Yeah that option is poorly named, should be basePath... The example blog's rss feed uses locals.url to create a permalink with the domain included.

**Comment by MrSaints** [comment]
Ah I see. I was not aware of this `article.getHtml(locals.url)`. Really useful! :) Thanks :+1:
