### ISSUE TITLE
Option to remove default content plugins

### ISSUE THREAD

**Issue by magedahmed** [jnordberg/wintersmith#281]
In case one wants to output raw *.md or *.json files. 

Plugins like this achieve this (wintersmith-data-json)[https://github.com/gadomski/wintersmith-data-json], achieve the functionality, but seems like it would be simpler to have it as a config.json option. 

I can make the pull request if the idea is approved.

**Comment by magedahmed** [comment]
Or a better alternative might be to have an ignore option - a list of regex expressions that if a file matches, it'll be ignored by all plugins.

**Comment by jnordberg** [comment]
There is an ignore option, but problem is that everything is plugins, even static files. So the file would not be copied over.

Usually i just create a simple plugin to the specific project to copy .json files over. Like so:

```coffee-script
module.exports = (env, callback) ->
  env.registerContentPlugin 'data', 'my/data/**', env.plugins.StaticFile
  callback()
```
