### ISSUE TITLE
Error with paginator plugin

### ISSUE THREAD

**Issue by gsouf** [jnordberg/wintersmith#293]
When doing ``wintersmith build`` or ``wintersmith preview``: 

```
TypeError: Cannot read property 'template' of undefined
  at /home/sghzal/laemon-blog/plugins/paginator.coffee:23:46
```

**Comment by jnordberg** [comment]
This is with an unmodified blog example?

**Comment by gsouf** [comment]
It was not, but it was kidda impossible to debug

**Comment by taktran** [comment]
I got the same problem when I deleted the `hello-world/index.md` content, and I couldn't get out of it, even after restarting `wintersmith preview`.

To fix it, I added an `if` check for `item.template` on https://github.com/jnordberg/wintersmith/blob/master/examples%2Fblog%2Fplugins%2Fpaginator.coffee#L23

ie,

```
    # skip articles that does not have a template associated
    articles = articles.filter (item) ->
      if item
        item.template isnt 'none'
```

Does it cache the previous data or something? I couldn't figure out why it wouldn't work even after a restart of `wintersmith preview`
