### ISSUE TITLE
Wintersmith build does not finish or return 0

### ISSUE THREAD

**Issue by jtorresfabra** [jnordberg/wintersmith#294]
I'm trying to write a shell script calling cli wintersmith build, but it seems wintersmith never returns control if it succeed. I always need to Ctrl-C to continue. Any clue or advise? Thanks

**Comment by jnordberg** [comment]
Can you reproduce it without any plugins?

**Comment by jtorresfabra** [comment]
I'm using the wintersmith-nunjucks plugin, so probably related.

**Comment by jtorresfabra** [comment]
Just calling wintersmith.build() from js does work. It happens only with cli.

**Comment by jnordberg** [comment]
Yep, was the nunjucks plugin. See jbuck/wintersmith-nunjucks#22

I'm going to add a process.exit as well to the cli, no point in allowing plugins to keep the process running after they call the callback

**Comment by jtorresfabra** [comment]
That would be great. Thanks!
