### ISSUE TITLE
Content-Tree in page.parent is incomplete (missing other content groups)

### ISSUE THREAD

**Issue by MaZderMind** [jnordberg/wintersmith#295]
In a Template and using `util.inspect` to inspect part of the Content-Tree. I'd like to access parts of the Content-Tree relative to the current Page. I found `page.parent` to be particularly useful, but when I installed `wintersmith-image-generator` which contains a `generator` I found that accessing `page.parent` would not give me the ContentTree-Items generated by it.

Considering this Template
```` jade
pre(style='color: green')
  = util.inspect(contents.pictures, {depth: 0})
pre(style='color: red')
  = util.inspect(page.parent.pictures, {depth: 0})

hr

pre(style='color: green')
  = util.inspect(contents.pictures._, {depth: 1})
pre(style='color: red')
  = util.inspect(page.parent.pictures._, {depth: 1})
````

would, for example, give me this output (green = accessed via the `content` variable, red = accessed via `page.parents`):
![screenshot from 2015-11-25 14 38 19](https://cloud.githubusercontent.com/assets/142237/11398619/65d2b89e-9382-11e5-8082-0fb320382d39.png)

I expected to be both ways to access the conten-tree to be equal. Is there a way to access the complete Content-Tree relative to the current `page`?

**Comment by jnordberg** [comment]
This is a bug, they should be equal.

Try adding  `item.parent = root` after this line and see if it fixes it
https://github.com/jnordberg/wintersmith/blob/master/src/core/content.coffee#L279

**Comment by MaZderMind** [comment]
Yep, that fixes it. Should i send in a PR?

**Comment by jnordberg** [comment]
Yes that would be great, thanks!
