### ISSUE TITLE
Hooking into 'wintersmith build'

### ISSUE THREAD

**Issue by boedlen** [jnordberg/wintersmith#299]
Is it possible to write a plugin that hooks into the 'wintersmith build' event?

I'd like to use a tool like www.contentful.com for managing my content, and generate `*.md` files just before the HTML is being generated.

**Comment by jnordberg** [comment]
I think what you are after is the generator plugins, those hook in to the process letting you asynchronously create content from any source and inject it to the tree before building or previewing

**Comment by paesku** [comment]
Hi @boedlen 
I'm also receiving data from http://www.contentful.com/. Beside Products getting rendered from json Objects, I have normal Pages created in contentful which are exposed as Markdown.

I require lodash assinged to `_` and [marked](https://github.com/chjj/marked) assinged to `md` in my config and then in my jade file:
 
```jade
- var pages = contents['pages.json'].metadata.items
- var content = md(_.find(pages, function(a) { return a.fields.pageType == 'imprint'; }).fields.page);
  .primary-area
   !{content}
```
Which works fine.
