### ISSUE TITLE
Unsafe website link listed for wintersmith-tag example

### ISSUE THREAD

**Issue by logorrhea** [jnordberg/wintersmith#309]
The website listed on `https://github.com/jnordberg/wintersmith/wiki/Plugins` as an example for the `wintersmith-tag` plugin seems to lead to an unsafe webpage. It repeatedly spammed me with alerts.

**Comment by jnordberg** [comment]
Thanks for letting me know and feel free to edit the page, it’s a wiki :)

On 18 May 2016 at 17:26:48, Tyler Funk (notifications@github.com) wrote:

The website listed on https://github.com/jnordberg/wintersmith/wiki/Plugins as an example for the wintersmith-tag plugin seems to lead to an unsafe webpage. It repeatedly spammed me with alerts.

**Comment by logorrhea** [comment]
Oh, ok. Edit made, thanks :)
