### ISSUE TITLE
Sass not SASS

### ISSUE THREAD

**Issue by TheJaredWilcurt** [jnordberg/wintersmith#316]

**Comment by jnordberg** [comment]
Potato Tomato? :)

**Comment by TheJaredWilcurt** [comment]
If your site was about farming and everything you mentioned a list of crops like corn, lettuce, POTATOES, carrots, you put potatoes in all caps, you would be right.

It makes no sense to capitalize POTATOES. It, like the language Sass, is not an acronym. Sass *is* a proper noun however.

It has two different syntaxes denoted by two different filetypes.

* `.scss` uses Sassy Cascading Style Sheets (SCSS).
* `.sass` uses Syntactically Awesome Style Sheets (SASS).

When you are referring to the second syntax, it should be capitalized. However, when referring to the language itself, or the community around it, Sass is not an acronym and is just a proper noun, like Node, or Ruby.

**Comment by jnordberg** [comment]
I'll accept a PATCH ;)

**Comment by TheJaredWilcurt** [comment]
I think I've put in more than enough effort already. If you don't care enough about your project to change 3 characters, I can't see any reason why anyone would even use this thing.

**Comment by jnordberg** [comment]
Wow, your attitude sucks. Feel free not to use my thing
