### ISSUE TITLE
Feature Request: Adding custom markdown tags

### ISSUE THREAD

**Issue by jaskiratr** [jnordberg/wintersmith#322]
I've been using Wintersmith for a while now. It's awesome!

Though I end up a lot of times adding `html` in my `markdown` files. Which doesn't make it readable [e.g.](https://raw.githubusercontent.com/jaskiratr/portfolio/master/contents/articles/02-%20Quartz/index.md) I came across [markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) for nodejs and there are similar markdown packages for Ruby and Python. 

How would one go about using markdown-it-attrs with wintersmith? 

Thanks.

**Comment by jnordberg** [comment]
Thanks!

You could write a plugin for it, easiest would be to subclass the existing markdown plugin. Have a look at how it's done here: https://github.com/jnordberg/wintersmith/blob/master/src/plugins/markdown.coffee

**Comment by jaskiratr** [comment]
Thanks. I'll take a stab at it. :)
