### ISSUE TITLE
Beta release with Pug v2 support

### ISSUE THREAD

**Issue by sirodoht** [jnordberg/wintersmith#324]
I want to use wintersmith but our app has switched to Pug v2. I searched and found #308 about using Pug instead of Jade.

Pug is now at beta11 and it is very stable despite the beta tag.

However, to ensure stability wintersmith could also publish a beta version, using Pug v2 beta. I'd be willing to create a PR.

What do you think?

**Comment by jnordberg** [comment]
Yeah sure, it has to be done at some point anyways :)

**Comment by VaelynPhi** [comment]
I just did a simple sed/jade/pug/g (well, with a few special renames, like JadeTemplate to PugTemplate) and everything seems to work just fine. Let me know and I'd be happy to submit the pull request. I branched first (pug-migrate) but could easily merge back to master and rebase if you prefer single commits.

**Comment by sirodoht** [comment]
Yeah. Testing is where I got stuck too.

**Comment by jnordberg** [comment]
Create a PR with the changes and we can all test the same code

**Comment by VaelynPhi** [comment]
PR submitted; I was hoping to submit it as a new branch, but I'm not sure how to achieve that with Github, if possible at all. I'm mostly used to using git on the command line. Let me know if I can change anything that's helpful.

**Comment by jnordberg** [comment]
As of version 2.5.0 wintersmith uses pug, thanks @sirodoht @VaelynPhi @SuriyaaKudoIsc and @yusufhm!
